name: Run Nightly Pgskipper Pipeline

permissions:
  actions: write
  contents: read

on:
  workflow_dispatch:
    inputs:
      service_branch:
        description: 'Branch to run tests against'
        required: false
        default: 'main'
      skip_wait:
        description: 'Skip waiting for dev_build.yml to complete (use when images are already built)'
        required: false
        type: boolean
        default: false
  push:
    branches: [main]
    paths-ignore:
      - "docs/**"
      - "CODE-OF-CONDUCT.md"
      - "CONTRIBUTING.md"
      - "LICENSE"
      - "README.md"
      - "SECURITY.md"

jobs:
  Nightly-Pgskipper-Pipeline:
    uses: callmesi/qubership-test-pipelines/.github/workflows/pgskipper.yaml@3e4193378da5730d7b96d3a625d22a158d5e8372 #v1.12.0

    with:
      repository_name: ${{ github.repository }}
      service_branch: '${{ github.head_ref || github.ref_name }}'
      pipeline_branch: '3e4193378da5730d7b96d3a625d22a158d5e8372' #this value must match the value after '@' in 'uses'
      runner_type: 'ubuntu-latest'
      scope: 'nightly'
    secrets:
      AWS_S3_ACCESS_KEY_ID: ${{secrets.AWS_S3_ACCESS_KEY_ID}}
      AWS_S3_ACCESS_KEY_SECRET: ${{secrets.AWS_S3_ACCESS_KEY_SECRET}}
